### ISSUE TITLE
Why is a M-BUS slave board needed? (and not a master board)

### ISSUE THREAD

**Issue by B48D81EFCC** [DomiStyle/esphome-dlms-meter#35]
Hello,

I am wondering, why we need a slave board in this case?
I would assume that the ESP32 is the master and the meter (e.g. Kaifa)  is the slave.

I hope you can wipe out my lack of knowledge.

**Comment by DaPeace** [comment]
The Kaifa is the master and is just pushing the data to the slave one-way. Thats why you need a slave-board.

**Comment by B48D81EFCC** [comment]
Hi,

okay thanks! I am wondering why Kaifa is the master. Is it configurable? Can the Kaifa device be the slave?

If Kaifa is always the master, this would prevent to add other slaves to the M-Bus, isn't it?

**Comment by Soundrico** [comment]
you can add other slaves to the mbus eg water or gas meters, etc

**Comment by B48D81EFCC** [comment]
Ah sorry. Yes, other slaves can be added to the bus of course.
Hopefully the other devices like gas or water meters are not a master as well.

I was just surprised that the Kaifa device is a master, since M-Bus is a single master bus.
I think (for max. flexibility) the bus master should be a separate device.

Thanks for the clarification.
