### ISSUE TITLE
Help with M-Bus Slave

### ISSUE THREAD

**Issue by erik-toth** [DomiStyle/esphome-dlms-meter#43]
Hello!
I used a diffrent M-Bus Slave board and wanted to know if anyone has any experience with the "[replica board](https://a.aliexpress.com/_ExTx9lN)". 

![image](https://github.com/user-attachments/assets/8356aeac-8cc5-4fcc-b8dd-ca9011d243fd)

I have set up everything like the Hardware Installation in the read me recommends, but as a value in HA i just get "unknown". I already let it run for 1 hour, just to be sure. Now my question is: Might it be the board or something different I've done wrong. It seems like I don't receive any data.

Best regards Erik!

![image](https://github.com/user-attachments/assets/f39c1ee6-42c0-423d-9dfe-1303933e07dd)![image](https://github.com/user-attachments/assets/b8a2fc12-9f69-4448-bf24-1ca34f099697)

**Comment by SimonFischer04** [comment]
Hi,
I'm working on updating the component and eventual native integration into esphome.
You could try my version and see if it helps: https://github.com/SimonFischer04/esphome/issues/1

**Comment by erik-toth** [comment]
> Hi,
> 
> I'm working on updating the component and eventual native integration into esphome.
> 
> You could try my version and see if it helps: https://github.com/SimonFischer04/esphome/issues/1

Thanks for the reply and for looking into my question! I'll try your version and give you feedback if it works

**Comment by SimonFischer04** [comment]
So as you got it working, this issue can be closed now?
