### ISSUE TITLE
always gets Errors

### ISSUE THREAD

**Issue by homecineplexx** [DomiStyle/esphome-dlms-meter#6]
Hi
I tried this with different settings and always get this errors!
Maybe you can help me? would be great....thanks
greets chris

![ESPHome_problem](https://user-images.githubusercontent.com/43374575/144045049-e600be8c-f611-496b-9405-23548f83b241.png)

**Comment by DomiStyle** [comment]
Can you post your folder structure, config and details about your ESPHome setup?

**Comment by homecineplexx** [comment]
Here they are

[meter01.yaml (1).txt](https://github.com/DomiStyle/esphome-dlms-meter/files/7639459/meter01.yaml.1.txt)
![ESPHome_directory (Kopie)](https://user-images.githubusercontent.com/43374575/144368118-9c2ae7fc-38ef-4d19-89a5-0b89a1ce9477.png)

**Comment by DomiStyle** [comment]
Can you repeat the steps listed in the readme at https://github.com/DomiStyle/esphome-dlms-meter#software-installation?

Most noteably, your directory structure should look like this:

* config
  * meter01.yaml
    * esphome-dlms-meter
      * Contents of this repository (espdm.h, ...)

Make sure to remove any stray files from this repo you have added in your root config directory.

Change the includes line to this afterwards:

```
  includes:
    - ./esphome-dlms-meter
```

Don't include the .h file directly.

**Comment by homecineplexx** [comment]
ok i will try this in the evening and give you feedback!
thanks

**Comment by homecineplexx** [comment]
so i tried this, but there is the next or other error
![Path](https://user-images.githubusercontent.com/43374575/144482913-ff235136-42e5-4bf7-8688-7597850f859f.png)
![error_output](https://user-images.githubusercontent.com/43374575/144482922-962e74e5-886e-427d-a24d-50ad6527aa37.png)


[meter01.yaml.txt](https://github.com/DomiStyle/esphome-dlms-meter/files/7644344/meter01.yaml.txt)

**Comment by DomiStyle** [comment]
Can you try with the new version I just pushed? Don't forget to clean previous build files and edit your config:
`auto dlms_meter = new esphome::espdm::DlmsMeter(id(mbus));`

**Comment by homecineplexx** [comment]
ok, thanks, you are incredible. with the new version the compile works and i can test if the esp32 works with my smartmeter

thanks thanks thanks
